#ifndef DEFS_H
#define DEFS_H

#define WINDOW_WIDTH 1700
#define WINDOW_HEIGHT 900
#define MAX_ENEMIES 100
#define MAX_PLACED_BIRDS 20
#define MAX_PROJECTILES 100
#define PROJECTILE_SPEED 3500.0f

#define HIT_THRESHOLD 10.0f

#endif
